In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = pd.read_csv('Pakistan_Election_Results_1970_2013_Cleaned.csv')

/Users/zohaib/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (0,7,9,16,22,23,24,27,31,36,38,44,49,56,58,61) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [10]:
df.head()

,id_no,NA,NA1,NAName,sr,CandidateName,Party,party1,party_93,nnparty,...,Winner,ndivision,nZones_20,nRegions_12,Nregions_11,nprov,party_2013,ID_Respondent,n_Registerd,ap1
0,5201,1.0,1.0,NA-1 PESHAWAR-I,1,Haji Dost Mohammad,IND,138,102,75,...,,,,,,,,1.0,3.0,1.0
1,5202,NaN,1.0,NA-1 PESHAWAR-I,2,Haji Ghulam Ahmad Bilour,ANP,5,5,9,...,,,,,,,,2.0,3.0,1.0
2,5203,NaN,1.0,NA-1 PESHAWAR-I,3,Mr.Rifatullah,IND,39,39,88,...,,,,,,,,3.0,3.0,1.0
3,5204,NaN,1.0,NA-1 PESHAWAR-I,4,Syed Javed Hassan shah,IND,39,39,88,...,,,,,,,,4.0,3.0,1.0
4,5205,NaN,1.0,NA-1 PESHAWAR-I,5,Syed Zafar Ali Shah,PPP,124,124,1,...,,,,,,,,5.0,3.0,1.0